= Hive / HBase & Dataviz

== Usages

=== Hive vs. HBase - Difference between Hive and HBase

* Hive is query engine that whereas HBase is a data storage particularly for unstructured data.
* Apache Hive is mainly used for batch processing i.e. OLAP but HBase is extensively used for transactional processing wherein the response time of the query is not highly interactive i.e. OLTP.
* Unlike Hive, operations in HBase are run in real-time on the database instead of transforming into mapreduce jobs.
* HBase is to real-time querying and Hive is to analytical queries.

Hive -> high latency

=== Usage of MicroStrategy

* https://www2.microstrategy.com/producthelp/10.7/WebUser/WebHelp/Lang_1033/Content/mstr_big_data.htm :
	** voir la partie "Connecting and analysing Big Data sources in MicroStrategy", et plus particulièrement :
		*** interactive queries : solution d'intermédiation pour accéder à la data
			**** Impala plusieurs fois mis en avant (https://fr.slideshare.net/snehl17/hadoop-integration-with-microstrategy slide 8 / 19) +
			Apparemment 100x plus rapide que Hive
		*** NoSQL sources

Jetez un oeil à Microstrategy Hadoop Gateway ? (separate MicroStrategy proprietary installation) +
-> NON, probablement à ne pas choisir, actuellement l'opération JOIN n'est pas supportée.

* https://fr.slideshare.net/snehl17/hadoop-integration-with-microstrategy

See https://www.dezyre.com/article/hive-vs-hbase-different-technologies-that-work-better-together/322